server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true


spring:
  datasource:
    name: dev
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.196.37.10:4408/hbyd_game_web?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: root
    password: BJchuanyun252db
    driver-class-name: com.mysql.jdbc.Driver


